### ISSUE TITLE
Windows 8 Compatibility Issue?

### ISSUE THREAD

**Issue by albhardy** [t4t5/november-cli#2]
Hi Tristan, 
It hangs on Windows 8.1 Platform

![image](https://cloud.githubusercontent.com/assets/1732018/7832729/dd0293a4-0493-11e5-8edd-35d5419140a6.png)

The code terminates at `nov.novemberDir()` in new-project.js - removing the conditional check allows it to proceed. Also, it does not reach generate-model line 30 (it does not go inside `catch` section of the code).

**Comment by t4t5** [comment]
Ah, yes, I should probably have specified that it's not Windows compatible for now, since it runs some Unix commands. Sorry for that.

I don't really have the ability to port the library for now, do you think you could peek at the source code and help out...?

**Comment by albhardy** [comment]
I found the error is caused by `nov.novemberDir()`. Likely due to fs-finder compatibility in windows (https://github.com/sakren/node-fs-finder/issues/9).  I managed to run the app after removing those codes in generate-action, generate-model and nov.js

**Comment by billpull** [comment]
@albhardy could you create a PR for this or link to the changes would also like to run this on windows
